### ISSUE TITLE
gmrecords process step fails

### ISSUE THREAD

**Issue by bartikpandel** [DOI-USGS/ghsc-esi-groundmotion-processing#2]
I downloaded some ground motions using gmprocess 2.0.0. The assemble step worked fine but when I try to run the process command, the program exits with an error. Not entirely sure what's causing this issue.

INFO 2024-06-14 13:30:27 | process_waveforms.main: Running subcommand 'process_waveforms'
INFO 2024-06-14 13:30:27 | process_waveforms.main: Number of events to process: 2048
INFO 2024-06-14 13:30:27 | process_waveforms.main: Processing tag: default
INFO 2024-06-14 13:30:27 | process_waveforms.main: Processing waveforms for event texnet2017cxfh (1 of 2048)...
INFO 2024-06-14 13:30:27 | process_waveforms._process_event: Processing 'unprocessed' streams for event texnet2017cxfh...
INFO 2024-06-14 13:30:29 | processing.process_streams: Stream: TX.ALPN.HH
WARNING 2024-06-14 13:30:29 | warnings._showwarnmsg: /Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/waveform_processing/snr.py:257: RuntimeWarning: invalid value encountered in sqrt
  smooth_signal_normspectrum = smooth_signal_spectrum / np.sqrt(dur_shaking)

CRITICAL 2024-06-14 13:30:29 | gmrecords.main: 'str' object has no attribute 'copy'
Traceback (most recent call last):
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/apps/gmrecords.py", line 123, in main
    self.args.func().main(self)
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/subcommands/process_waveforms.py", line 59, in main
    self._process_event(event_id)
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/subcommands/process_waveforms.py", line 122, in _process_event
    processing.process_streams(
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/waveform_processing/processing.py", line 135, in process_streams
    step_args = processing_step_dict[step_name].copy()
AttributeError: 'str' object has no attribute 'copy'

Args: 
    debug: False
    quiet: False
    log: None
    event_id: None
    textfile: None
    label: None
    num_processes: 0
    overwrite: False
    datadir: None
    confdir: None
    subcommand: process
    reprocess: False
    func: <class 'gmprocess.subcommands.process_waveforms.ProcessWaveformsModule'>
Project Name: M 2-
Conf Path: /Users/bp_macbookair/Research/Seismometer Data/M 2-/conf
Data Path: /Users/bp_macbookair/Research/Seismometer Data/M 2-/data

Traceback (most recent call last):
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/bin/gmrecords", line 10, in <module>
    sys.exit(main())
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/bin/gmrecords.py", line 6, in main
    GMrecordsApp().main()
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/apps/gmrecords.py", line 137, in main
    raise e
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/apps/gmrecords.py", line 123, in main
    self.args.func().main(self)
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/subcommands/process_waveforms.py", line 59, in main
    self._process_event(event_id)
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/subcommands/process_waveforms.py", line 122, in _process_event
    processing.process_streams(
  File "/Users/bp_macbookair/anaconda3/envs/gmprocess_2.0/lib/python3.10/site-packages/gmprocess/waveform_processing/processing.py", line 135, in process_streams
    step_args = processing_step_dict[step_name].copy()
AttributeError: 'str' object has no attribute 'copy'

**Comment by emthompson-usgs** [comment]
@bartikpandel This is a bit of a mystery. I suspect that this is an issue in the specification of the processing steps in the config file. Can you post the `processing:` section of your config file? Please do this by opening the yml file that should be present in in the `/Users/bp_macbookair/Research/Seismometer Data/M 2-/conf` directory.

**Comment by bartikpandel** [comment]
Hi Eric, yes you are correct. It was a typo in my config file. Instead of a ':', I had an '=' sign which was causing the issue. The program runs fine after I fixed the typo. Thank you so much!
